version: '3'

services:
  orders-db:
    container_name: orders-database
    image: postgres:16.2 # Usar la base de datos que necesite, en este caso, postgres
    restart: always
    volumes:  # Volumen para persistir la base de datos
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders 